### ISSUE TITLE
Allow extension to use self hosted infracost endpoint and key

### ISSUE THREAD

**Issue by Shocktrooper** [infracost/vscode-infracost#140]
Like the title it would be cool to allow the extension to use a self hosted installation of infracost vs purely the SAAS version.  This alleviates some of the problem some organizations have where there is an air-gapped network with outbound traffic restricted or proxies for outbound traffic.

**Comment by alikhajeh1** [comment]
@Shocktrooper you can already do this by running `infracost configure set pricing_api_endpoint https://my-cloud-pricing-api` (check `infracost configure --help` for other config options).

**Comment by Shocktrooper** [comment]
@alikhajeh1 maybe we could add this to the docs then. I could not find this information anywhere or maybe I am just blind.

**Comment by alikhajeh1** [comment]
@Shocktrooper good point! I added https://github.com/infracost/docs/pull/456 just now
