### ISSUE TITLE
Unable to login when using a remote container

### ISSUE THREAD

**Issue by jacobwoffenden** [infracost/vscode-infracost#191]
When trying to "Connect VSCode to Infracost", nothing happens. I can see process being spawned, but it doesn't open a browser

<img width="1582" alt="Screenshot 2023-08-10 at 12 39 42" src="https://github.com/infracost/vscode-infracost/assets/15148673/c1afa595-48bd-4526-b91a-30d37853cbb3">

Running `infracost auth login` in the terminal displays the URL that I can click and open, and then authenticate, but then VSCode cannot use this token

**Comment by vdmgolub** [comment]
Hello! The `infracost auth login` would work on local machine. If you want to run Infracost on a remote one, you'd need to do couple extra steps. From our [Troubleshooting section](https://github.com/infracost/vscode-infracost#troubleshooting):
1. Register for a free API key from [here](https://dashboard.infracost.io/). This is used by the extension to retrieve prices from our Cloud Pricing API, e.g. get prices for instance types.
2. [Install](https://www.infracost.io/docs/#1-install-infracost) the infracost CLI.
3. Run `infracost configure set api_key MY_API_KEY_HERE`.
4. Re-open the VSCode extension, it should now skip the "connect to Infracost" step as it uses the same API key from the CLI.

Hope this helps :)

**Comment by jacobwoffenden** [comment]
Shame on me for not reading the docs!

Thanks, @vdmgolub
