### ISSUE TITLE
Extension calculation is not perform when ressources are not evaluated

### ISSUE THREAD

**Issue by matthieupetite** [infracost/vscode-infracost#200]
When a resource is not evalutated, the Costs is set to NaN (or undefined) causing the sum to be also set to NaN, can it be changed to have a result calculation working. 

Here is a screenshot showing the issue.

![image](https://github.com/infracost/vscode-infracost/assets/4076681/471450f8-6ec8-4e7a-b5d5-6f5bceaeadf0)

The extension version is v0.2.17

**Comment by aliscott** [comment]
@matthieupetite thanks for reporting 🙏. This is on our current sprint to fix this issue.

**Comment by matthieupetite** [comment]
Good news and thanks a lot

**Comment by hugorut** [comment]
another user reported a replicable example of this on an issue in the `infracost/infracost` repo, see: https://github.com/infracost/infracost/issues/2662#issue-1897097788

**Comment by hugorut** [comment]
Thanks for reporting @matthieupetite, this issue has been fixed in the [v0.2.18](https://github.com/infracost/vscode-infracost/releases/tag/v0.2.18) release.
