### ISSUE TITLE
Support Infracost config files

### ISSUE THREAD

**Issue by hugorut** [infracost/vscode-infracost#7]
The Infracost VSCode extension has multi-project support through native auto-detection. However, many users might have variables and settings supplied through an Infracost config file. We should allow users to supply config files through an extension setting or through parsing a common name/location.

---
Note for community
Please 👍 if you'd like to upvote this or receive updates.
Add a comment if you'd like to [contribute](https://github.com/infracost/vscode-infracost#contributing).

**Comment by alikhajeh1** [comment]
@hugorut now that config files can also support template syntax, could the extension detect if the config file has template syntax and run `infracost generate config` and use the generated file?

**Comment by hugorut** [comment]
can do

**Comment by hugorut** [comment]
Hello all, we've added config file support as part of the [0.2.11](https://github.com/infracost/vscode-infracost/releases/tag/v0.2.11) release. Please give it a whirl and let us know any bugs you find. 🙏 .
