### ISSUE TITLE
Could not run the infracost cmd in the directory.

### ISSUE THREAD

**Issue by IPvPho** [infracost/vscode-infracost#9]
"If this is a multi-project workspace please try opening just a single project. If this problem continues please open an issue here:"

I continue to receive this message within ll of my different TF directories no matter the structure.

I have installed infracost, registered or an API key, and enabled the extension within VS Code. 

<img width="373" alt="image" src="https://user-images.githubusercontent.com/46278866/176426182-6f9ff6b5-6d06-494c-9246-6f958fdbe917.png">

**Comment by hugorut** [comment]
@IPvPho did you get this working in the end?
